### ISSUE TITLE
UI/UX Improvements - Loading, Scrollbar, Particles

### ISSUE THREAD

**Issue by scs0209** [scs0209/3d-blog#32]
# UI/UX 통합 개선 - 로딩화면, 스크롤바, 파티클 효과

### 1. 로딩 화면 개선
**문제**: 로딩 애니메이션이 화면 중앙에 오지 않음
**해결**: 고정 위치 오버레이 및 중앙 정렬 적용
```typescript
// 개선 후  
<div className="fixed inset-0 flex items-center justify-center bg-black/50 backdrop-blur-sm z-50">
```

### 2. 스크롤바 스타일링 개선
**문제**: 스크롤바가 너무 화려하고 방해가 됨
**개선 과정**: 복잡한 그라데이션 → 단순화 → 미니멀 투명 디자인

**최종 버전**:
```css
::-webkit-scrollbar {
  width: 6px;
}
::-webkit-scrollbar-track {
  background: rgba(6, 182, 212, 0.2);
}
::-webkit-scrollbar-thumb {
  background: rgba(6, 182, 212, 0.3);
}
```

### 3. 사이드바 파티클 효과
**문제**: SparklesCore가 페이지 전체를 덮어버림
**해결**: 사이드바 옆에 위치하도록 절대 포지셔닝 적용

```typescript
<SparklesCore
  particleColor="#06b6d4"
  particleDensity={120}  // 기존: 1200에서 대폭 감소
  className={`absolute top-0 h-full w-1 transition-all duration-300 ${
    isOpen ? 'right-80' : 'right-0'
  }`}
/>
```

## 성능 최적화
- 파티클 밀도 감소: 1200 → 120
- AnimatePresence 외부로 이동하여 상태 유지
- transition-all duration-300으로 부드러운 전환

## 관련 파일
- `app/(public)/blog/loading.tsx`
- `app/globals.css`
- `src/widgets/post/ui/Sidebar.tsx`
